Update copy and commit.yml

diff --git a/.github/workflows/copy and commit.yml b/.github/workflows/copy and commit.yml
--- a/.github/workflows/copy and commit.yml
+++ b/.github/workflows/copy and commit.yml
@@ -27,12 +27,12 @@ jobs:
         git -C Getting-used-to-Pandas/ push origin main
       if: success()
 
-    - name: Ignore errors and continue
-      run: exit 0
+    # - name: Ignore errors and continue
+    #   run: exit 0
 
-    - name: Final check if file exists in source repository
-      run: |
-        if [ -f "local_getting_used_pandas.ipynb" ]; then
-          echo "File exists in source repository. This is an error."
-          exit 1
-        fi
+    # - name: Final check if file exists in source repository
+    #   run: |
+    #     if [ -f "local_getting_used_pandas.ipynb" ]; then
+    #       echo "File exists in source repository. This is an error."
+    #       exit 1
+    #     fi
